# Generated by Django 5.2.3 on 2025-07-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='contact',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
